CREATE TABLE links (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
    url_from VARCHAR(128) NOT NULL,
    url_to VARCHAR(128) NOT NULL,
    `key` BLOB NOT NULL,
    time TIMESTAMP NOT NULL,
    clicks INTEGER NOT NULL DEFAULT 0
);
