CREATE TABLE links (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    url_from VARCHAR NOT NULL,
    url_to VARCHAR NOT NULL,
    key BLOB NOT NULL,
    time TIMESTAMP NOT NULL,
    clicks INTEGER NOT NULL DEFAULT 0
);
